apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-webhook
webhooks:
- name: validate-webhook.test.com
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    url: https://server.webhook.com:5000/validate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwekNDQW8rZ0F3SUJBZ0lVZmZQTEZxdi9IdndwcVI2c1FURHQyV3AybzdFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lqRUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpERWJNQmtHQTFVRUF3d1NZMkZqWlhKMExuZGxZbWh2CmIyc3VZMjl0TUNBWERUSTBNRGd5TVRFek5UTXpPRm9ZRHpNd01qTXhNakl6TVRNMU16TTRXakJpTVFzd0NRWUQKVlFRR0V3SkJWVEVUTUJFR0ExVUVDQXdLVTI5dFpTMVRkR0YwWlRFaE1COEdBMVVFQ2d3WVNXNTBaWEp1WlhRZwpWMmxrWjJsMGN5QlFkSGtnVEhSa01Sc3dHUVlEVlFRRERCSmpZV05sY25RdWQyVmlhRzl2YXk1amIyMHdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzNqZFh0MXR0cSttZy9zb1llTTFiU241MjYKL2hPREhjT0FFTzcxWEZ5SmNVNjJOeWNJVW5HRnZwOWhXRVdFMXdDWVBzVlp2TW5aQ1FwM2hZTFRwWGluMnBJRApTYlBDa2VoMTdacDhDUkltTHlvaTRqNEFrWDg0aWgxREtEb1JpUUFnWmpZTjEvSWx4bUVPQ1NtRXQ2NzgyQVllCjJKbDk0b0pEemZ6eWhrd09tcVIwci83T3FEbjZmMnNqSm91NFpnUTNjSXRML0pCSjROa0dCM3hmQUZ4aWdqM08KcTJHTHdUdEk1TVZaU0haOGQweDNTTHF6ODlSWEQyd1AwaVp0TVJsN1d1YTJvdVEramZIdEtxbit6Z04xMmxPcQpIL21NbWxJSlBhNkNRTlVFeEMwbGQwcmE4K1lvUlB0UjZkZ1pHbzUxajF4cXNRT2tDZzJvYVVGMnlpbWRBZ01CCkFBR2pVekJSTUIwR0ExVWREZ1FXQkJSK3EwYnpKZ2xJcXBvL3F1Yml1OUNLNmZ4cGdUQWZCZ05WSFNNRUdEQVcKZ0JSK3EwYnpKZ2xJcXBvL3F1Yml1OUNLNmZ4cGdUQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNrZmZEN2V2WURXc3FRVzVjWmhocy9Wc0hNOHU5bWdwTjhxOVNya1ZOV3BUSkdoQjJFCmVZQ0tyeTdiS0o4amJCSjZKRk4yb25tby9MM2pYMk5qWC9ZSXZOMFhQWENaUjVSQWh0VVFmN1pGaFBSL1ZYck4KVXQ5dlQzdHVMWGx4WDJqU3VYb3JyZnlOZWpXMm16am9ocEhBWGVLZTBjRDJobWJJYis0SXJmSGQ1M1Rpc1NhMwpjZXZxRnhzamRBWDNrdVRYYWRNQm9iOTA1RXorSGZjNDEwM2d5U1dOYndTYTdWZU1zakJoc2xWTzAzVmJmdGVGCnBaaVhBMGpFYVh5M1dKclExOVZXMXBxTXJxK1RSRlEyclZlZ1p6ZDRNSld4am15QzU1Tys3QUUxc2F4dEtRdzAKNUhhS1VHRUErZ1JuNHVnRTVqTTJZZGdwV2x5Vkl6VkQydmFyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K 
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
